CREATE TABLE users (
  ID INT UNSIGNED NOT NULL,
  NAME VARCHAR(40) NOT NULL UNIQUE,
  EMAIL VARCHAR(40) NOT NULL UNIQUE,
  PASSWORD_HASH CHAR(100) NOT NULL,
  LANGUAGE_CODE CHAR(2),
  ROLE TINYINT UNSIGNED NOT NULL,
  STATUS VARCHAR(40),
  PRIMARY KEY (ID)
);
